name: Add Locales

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions: write-all

jobs:
    missing:
        uses: Laravel-Lang/.github/.github/workflows/locales.yml@main
