name: transfer issue

on:
    issues:
        types:
            - opened

permissions: write-all

jobs:
    issue:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Transfer issue
                uses: lando/transfer-issue-action@v2
                with:
                    token: ${{ secrets.COMPOSER_TOKEN }}
                    router: lang:Laravel-Lang/common
                    apply_label: lang
                    create_stub: true
