name: transfer issue

on:
    issues:
        types:
            - labeled

permissions: write-all

jobs:
    issue:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Transfer issue
                uses: lando/transfer-issue-action@v2
                with:
                    token: ${{ secrets.COMPOSER_TOKEN }}
                    router: lang:common
                    apply_label: lang

            -   name: Update Transferred Issue
                uses: actions/github-script@v5
                if: steps.transfer-issue.outputs.new_issue_number != ''
                with:
                  script: |
                    await github.rest.issues.createComment({
                      issue_number: `${{ steps.transfer-issue.outputs.new_issue_number}}`,
                      owner: context.repo.owner,
                      repo: `${{ steps.transfer-issue.outputs.destinatiom_repo }}`,
                      body: `@${ context.payload.issue.user.login }, your issue has been transferred to the main repository!`
                    });
